version: '2'
services:
  httpd:
    build:
      context: .
      dockerfile: ./docker/httpd
    ports:
      - 8008:80
    volumes:
      - ./data:/var/www/html
    networks:
      - sfycas

  phpfpm:
    image: "php:7.4-fpm-buster"
    expose:
      - 9174
    volumes:
      - ./data:/var/www/html
    networks:
      - sfycas

networks:
  sfycas:
    driver: bridge
